default_context:
  _pegasus_version: '2023.10'
  author_name: yong
  ci: github_actions
  css_framework: bulma
  css_theme: default
  database: sqlite
  deploy_platform: none
  description: AI writer specifically developed for academic
  docker_setup: arm64
  domain_name: onewriter.ai
  email: yong@onewriter.ai
  enable_google_login: n
  enable_twitter_login: n
  front_end_framework: htmx
  include_static_files: y
  marketing_email_platform: none
  post_process: n
  project_name: Academic AI Writer
  project_slug: onewriter_web
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: stripe_hosted
  use_2fa: y
  use_admin_docs: n
  use_api_keys: n
  use_async_example: y
  use_cloud_media_storage: n
  use_debug_toolbar: n
  use_docker: n
  use_ecommerce_example: y
  use_examples: y
  use_impersonation: y
  use_openai: n
  use_sentry: n
  use_subscriptions: y
  use_teams: n
  use_teams_example: n
  use_translations: y
  use_wagtail: y
