# Generated by Django 4.2.5 on 2023-10-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
    ]
